### ISSUE TITLE
Финансовые цели

### ISSUE THREAD

**Issue by pihel** [pihel/cash#2]
Цели в планировании

**Comment by pihel** [comment]
* Проверить установку: через сервис и локальную
* Сделать upgrade для уже установленных

**Comment by pihel** [comment]
* Добавить фактическую дату выполнения цели
* Добавить фильтр с возможностью показать выполненные цели (поумолчанию скрыт)
* Поправить высоту окна

**Comment by pihel** [comment]
Сделал, тестирую

**Comment by AlexeySa** [comment]
Решил протестировать с боевой базой данных на тестовом сервер. Получил ошибку о том, что не найдена тамблица "cashes_goal". Скопировал её структуру из оригинальной базы и всё заработало.

**Comment by pihel** [comment]
Поправил случай, когда таблица с целями еще не существует.
