### ISSUE TITLE
Сделать опцию запрета редактирования записей другим пользователем базы

### ISSUE THREAD

**Issue by AlexeySa** [pihel/cash#31]

**Comment by pihel** [comment]
Имеется в виду изменение записей другого пользователя одной базы?
Потому что иначе можно забрать права write и пользователь целиком не сможет редактировать/добавлять записи.

**Comment by AlexeySa** [comment]
Да, я имел в виду запрет изменения записей другого пользователя одной базы. Например, жена может что-то клацнуть не то и поудалять мои записи.
Если забрать права write, то и добавить в базу пользовтель ничего не сможет :(.

**Comment by pihel** [comment]
Добавил в настройки "Запрет редактирования чужих записей" - настройка общая для всей бд, т.е. будет распространяться на всех пользователей.
