### ISSUE TITLE
Ошибка csrf

### ISSUE THREAD

**Issue by AlexeySa** [pihel/cash#32]
Если накатить дистрибутив не в корневой каталог сервера, а в отдельную папке, то скрипт не загружается из-за ошибки csrf. Приходится обращаться на прямую к index.php.

http://example.com/buhcatalog/index.php - работает
http://example.com/buhcatalog/ - не работает из-за ошибки в функции csrf

**Comment by pihel** [comment]
Поправил, обновите файлы из commit https://github.com/pihel/cash/commit/ae4d460a6a91b05b1b546f148143bd1a085f25d0 или все целиком, кроме файла базы.
