### ISSUE TITLE
Ошибка при изменении или добавлении записи

### ISSUE THREAD

**Issue by AlexeySa** [pihel/cash#33]
Если указать магазин "220-volt", то запись не добавляется. Если указать такой магазин у уже существующей записи, то она удаляется.

**Comment by pihel** [comment]
Поправил проблему имен магазинов с цифрами, но осталась ошибка, если название магазина целиком из цифр. Тут я никак не могу отличить передано название или число из авто подстановки.
В этом случае подставится магазин под ID = числу из поля организации, т.е. фактически другая организация.
Так что советую использовать хотя бы одну букву в названии магазина.

Или есть предложения как обойти эту проблему? Пока приходит на ум - закрыть возможность добавления записей с магазином целиком из цифр.

**Comment by AlexeySa** [comment]
Спасибо за исправление. Мне кажется, что проще исключить цифровые магазины вообще, как вы и предложили.

**Comment by pihel** [comment]
Оставил предыдущую реализацию.
