### ISSUE TITLE
Добавление операции

### ISSUE THREAD

**Issue by AlexeySa** [pihel/cash#37]
Подскажите, можно ли добавить операцию в базу одним http-запросом? Нужно для стороннего приложения.

**Comment by pihel** [comment]
Вообще можно, POST запросом к странице https://github.com/pihel/cash/blob/master/ajax/add.php , пример запроса есть в комментарии файла или можно отловить ajax запрос у реально приложения.
Но тут будут проблемы с CSRF защитой, т.к. она работает через сессии, а у стороннего приложения сессии не будет ( https://github.com/pihel/cash/blob/master/lib/functions.php#L49 , https://github.com/pihel/cash/blob/master/lib/init.php#L43 ).
Проще всего отредактировать строчку https://github.com/pihel/cash/blob/master/lib/init.php#L43 - отключить CSRF проверку по значению какой-то переменной и устанавливать ее при обращении к ajax/add.php из приложения.

**Comment by AlexeySa** [comment]
А как в этом случае передать логин и пароль?

**Comment by pihel** [comment]
Про самое главное и забыл.
Перед запросами нужно авторизироваться, для этого нужно отправить POST запрос странице https://github.com/pihel/cash/blob/master/ajax/login.php
Параметры: login_db_name_list_cb=ИД_БАЗЫ&login_usr_name_list_cb=ИД_ЛОГИНА&password=ПАРОЛЬ&login_lang_list_cb=ИД_ЯЗЫКА&xcsrf=ТОКЕН_CSRF.

Кстати, токен CSRF для текущего пользователя, можно достать, распарсив JS страницы, он будет в JS переменной settings.csrf . Так что править init.php не обязательно, можно просто передавать эту переменную во всех POST запросах.

**Comment by pihel** [comment]
Закрою, ответ был дан.
