### ISSUE TITLE
Установка сломана

### ISSUE THREAD

**Issue by deseven** [pihel/cash#40]
Делаю банальный git clone, после начала установки невозможно выбрать язык, установка не завершается.
Начал ковыряться в исходниках, стало лень, создал базу на homebuh.pro, скачал и подсунул как cash.db3 - выбор языка появился и установка прошла успешно.

P.S. Спасибо за проект, пул-реквесты принимаете?

**Comment by pihel** [comment]
Да, конечно принимаются. Попытаюсь разобраться в ближайшее время.

**Comment by deseven** [comment]
Сегодня поставил чистый дистр CentOS 6 для экспериментов и все установилось без ошибок, воспроизвести старое поведение не удалось. Возможно это какие-то особенности sqlite? Там где я ставил первый раз стоит CentOS 5 и sqlite собран вручную. Хотя версия php (5.3.3) и версия sqlite3 (0.7-dev) совпадают и там и там.
В общем наверное это стоит закрыть, раз кроме меня никто не напоролся. Разве что можно было бы наверное error_reporting() включать на время установки.

**Comment by deseven** [comment]
Нашел проблему, посмотрев историю ввода команд. После git clone сделал chown изначально не на ту папку :) Закрываю, извините за беспокойство.
