### ISSUE TITLE
Не обрабатывается изменение размеров окна браузера

### ISSUE THREAD

**Issue by michaelkl** [pihel/cash#50]
При изменении размера окна браузера содержимое не перерисовывается. Если потом пощёлкать по вкладкам, то правые столбцы таблиц могут становиться недоступными.

**Comment by pihel** [comment]
Ресайз окна в extjs решается достаточно сложно. Как вариант сейчас можно просто обновить страницу, все фильтры при этом должны сохраниться, но размеры элементов будут пересчитаны под новый размер .

**Comment by michaelkl** [comment]
ok, понял.

**Comment by pihel** [comment]
Насколько понял, такой вариант подошел, так что закрою задачу.
