### ISSUE TITLE
Chrome/Opera: не определяется геопозиция

### ISSUE THREAD

**Issue by pihel** [pihel/cash#57]
Гео позиционирование в chrome работает только при https
http://stackoverflow.com/questions/32106849/getcurrentposition-and-watchposition-are-deprecated-on-insecure-origins
непонятно как обойти эту проблему

**Comment by michaelkl** [comment]
Алексей, по вашей ссылке на SO предложили workaround с Google Maps API. Не пробовали?
А вообще, почему бы не перейти на HTTPS? Для бухгалтерии это, я думаю, вещь жизненно необходимая.
Я столкнулся с аналогичной проблемой сейчас. Решил в итоге просто принудительно перенаправлять посетителей на HTTPS.

**Comment by pihel** [comment]
@michaelkl https был бы идеальный вариант, но бухгалтерию можно ставить на локальный хост, хотелось бы чтоб там тоже работало.
А сколько стоит самый дешевый ssl сертификат и будет ли он работать на поддоменах?

**Comment by michaelkl** [comment]
@pihel На локальном хосте вообще можно обойтись самоподписанным сертификатом.
А в интернете сейчас можно и бесплатно получить: StartSSL или Let's Encrypt советую посмотреть.

**Comment by pihel** [comment]
Сделал вариант позиционирования через google maps, если через браузер не удалось определить положение. Первое впечатление - очень низкая точность до города, даже если добавлять товар через телефон с улицы.
Буду тестить дальше, возможно, придется переходить на https.

**Comment by michaelkl** [comment]
@pihel Посмотрел вашу реализацию. Зацепился глазом за это:
```
if(error.code == error.PERMISSION_DENIED &&
   error.message.indexOf("Only secure origins are allowed") == 0) {
```
Я бы не стал использовать сообщение из `error.message` таким образом, поскольку оно не стандартизовано. Вот что W3C [пишет в спецификации](https://dev.w3.org/geo/api/spec-source#position_error_interface):

> The `message` attribute must return an error message describing the details of the error encountered. This attribute is primarily intended for debugging and developers should not use it directly in their application user interface.

**Comment by pihel** [comment]
@michaelkl вы правы, закомментил проверку по тексту, оставил только по коду

**Comment by pihel** [comment]
Потестировал некоторое время, позиция через google.maps определяется, хоть и сильной погрешностью. Через https все бы работало как раньше.
