### ISSUE TITLE
Альтернативные базы данных

### ISSUE THREAD

**Issue by AircraftRu** [pihel/cash#62]
Предложение сделать поддержку альтернативной базы, таких как MySQL для тех кто может и хочет ее использовать, тем более для быстрой и с большими данными работе отлично подходит. На OpenServer легко поставить ваше приложение и легко настраивать для работы с любой базой.

**Comment by pihel** [comment]
Способы подключения других бд описывалось здесь: https://github.com/pihel/cash/issues/45#issuecomment-140127861

**Comment by AircraftRu** [comment]
Я не состоявшийся пока разработчик на php, так что мне сложно понять, что нужно прописать, разве что понимаю что нужно require прописать, но так не работает.

**Comment by AircraftRu** [comment]
По тому, куда вы направили вообще не понятно как подключить MySQL, там и близко про это не написано.

**Comment by pihel** [comment]
Установка на Mysql базу:
1. Создаем mysql базу
2. Создаем таблицы скриптом: https://github.com/pihel/cash/blob/master/data/mysql_install.sql
3. Меняем в настроечном файле https://github.com/pihel/cash/blob/master/lib/init.php#L11
переменную $db_name на MYSQL:
`$db_name = 'MYSQL';`
4. Устанавливаем настройки подключения в файле на строке: https://github.com/pihel/cash/blob/master/lib/init.php#L52
`$conf = array('srv' => 'localhost', 'login' => 'root', 'pasw' => '', 'db' => 'cash');`
5. Выполняем обычную установку
