### ISSUE TITLE
Ввод суммы с точкой в качестве разделителя

### ISSUE THREAD

**Issue by AlexeySa** [pihel/cash#64]
Предлагаю маленький, но очень полезный фикс. На форме добавления/редактирования операций сделать возможность вводить сумму с точкой, а во внутренней логике уже заменять её на запятую.

**Comment by pihel** [comment]
Где то было в Issues или я просто смотрел. 
Помню, что были проблемы с extjs, где разделитель для числовых полей не настраивается и как это обойти я быстро не нашел.
Так что не очень простая задача получается.
Как быстрый вариант в голову приходит только заменить тип поля с числового на текстовое.

**Comment by pihel** [comment]
Добавил замену ",бю" на "." через js. Как такой вариант?

**Comment by AlexeySa** [comment]
Обновился. Но что-то не получается ввести в поле суммы что-то другое кроме цифр и точки. Замены нет. Если вставить сумму по Ctrl+V, то запятая и всё, что за ней отбрасывается. 11,33 превращается в 11.

**Comment by pihel** [comment]
Да, вроде, все выложил. У меня в demo тоже не сразу заработало, после пары сбросов кэша. Это не помогает?

**Comment by AlexeySa** [comment]
Действительно, после очистки кэша заработало. Спасибо!
