### ISSUE TITLE
Ошибка при использовании базы MySQL

### ISSUE THREAD

**Issue by AircraftRu** [pihel/cash#65]
Привет, я давно нашел и исправил ошибку   `require_once($root.'lib/db/filecachdb.php');` в `init.php`, добавил ее через редактор GitHub, но до сих пор не принята, так что сообщаю через раздел проблем. Исправлено на  `require_once($root.'lib/db/filecachedb.php');` , "e" не хватало в слове "cache".

**Comment by pihel** [comment]
Привет, попробуйте сделать fork моего репозитория, поправить ошибку, а потом перенести изменение через Pull request в мой.
Вроде так делается

**Comment by AircraftRu** [comment]
Я так сделал. Интересно почему я первый так делаю, но есть исправляющие код и другие.

**Comment by pihel** [comment]
Спасибо, смержил: https://github.com/pihel/cash/pull/66
