### ISSUE TITLE
Проблема со временем

### ISSUE THREAD

**Issue by AircraftRu** [pihel/cash#70]
Привет,
при открытии настроек и просмотра пользователей не отображается [дата последнего входа](https://github.com/pihel/cash/blob/master/lib/settings.php#L22) , хотя в базе записана.

Так же ругается на синтаксис MySQL кода (`datetime(CURRENT_TIMESTAMP, 'localtime')`) при [создании нового пользователя](https://github.com/pihel/cash/blob/master/lib/settings.php#L75), собственно и не создает.

**Comment by AircraftRu** [comment]
Мне даже интересно как ты решишь это, сам пытался найти решение, но не нашел.

**Comment by pihel** [comment]
Поправил эту проблему и еще несколько, которые нашел параллельно.
Я mysql версией не пользуюсь, так что наличие ошибок достаточно вероятно.
Проверьте пожалуйста, что тебе все хорошо.
