### ISSUE TITLE
Не отображается oper-дата

### ISSUE THREAD

**Issue by beloniki** [pihel/cash#73]
Версия 1.082 - сабж в листинге операций, хотя данные прилетают от сервера.

**Comment by pihel** [comment]
@beloniki это в sqlite версии или в mysql?
в sqlite вроде все нормально отображается http://demo.homebuh.pro/#act=list&from=2017-05-02&to=2017-05-09

**Comment by beloniki** [comment]
Версия mysql. В базе поле data заполнено.
В sqlite версии действительно всё отображается.
Заметил только, что с mysql дата приходит со временем, а в sqlite - без него.

**Comment by beloniki** [comment]
Кажется нафиксировал: сменил тип поля date с DATETIME - на DATE. Время из ячеек исчезло и дата стала отображаться в вебе.

**Comment by AircraftRu** [comment]
Привет. Это связано с #70

**Comment by beloniki** [comment]
Это связано с тем, что в js у них разное представление?

**Comment by pihel** [comment]
@beloniki спасибо, много не разбирался в причинах проблемы
скрипт установки поменял
Для существующих баз предлагаю просто проальтерить поле в базе
`alter table `cashes` modify `date` DATE NOT NULL`
