### ISSUE TITLE
Не сохраняются справочники

### ISSUE THREAD

**Issue by beloniki** [pihel/cash#74]
Версия mysql: в результате изменений в разделе "справочники", возникает ошибка "-1" при попытке сохранения.
В версии sqlite традиционно всё хорошо :)

**Comment by pihel** [comment]
Поправил.

**Comment by beloniki** [comment]
Теперь выдаёт Ошибка "0". ЧЯДНТ?

**Comment by pihel** [comment]
На каком из справочников получается ошибка?

**Comment by beloniki** [comment]
Попробовал все - одинаковая картина.

**Comment by pihel** [comment]
@beloniki Проверьте с этими исправлениями

**Comment by beloniki** [comment]
Да, теперь работает. Однако, если не изменить строку и нажать сохранить, то прилетает ошибка 0.

Пока искал причину, тоже пытался сделать `if (is_array($args['1'])) $args=$args['1'];` функции exec в db.php, но всё крашилось :)

**Comment by pihel** [comment]
0 - это не ошибка, это значит, что в обновляемой строке ничего не поменялось.
я для этого поменял еще static/js/refbooks.js
проверьте, что справочник сохраняется, если в нем что-то поменять.
